[enum.Department]
values = [
    "WEBOPS",
    "FINANCE",
    "SPONSORSHIP_AND_PR",
    "SHOWS_AND_EXHIBITIONS",
    "ENVISAGE",
    "EVOLVE",
    "EVENTS_AND_WORKSHOPS",
    "PUBLICITY",
    "CONCEPT_AND_DESIGN",
    "OPERATIONS_AND_INFRASTRUCTURE_PLANNING",
    "ADMIN",
    "QMS"
]

[enum.UserRole]
values = ["COORDINATOR", "HEAD", "CORE", "COCAS", "COCAD"]

[model.User]
[model.User.id]
type = "String"
attributes = ["@generated", "@unique", "@uuid"]

[model.User.name]
type = "String"

[model.User.email]
type = "String"
attributes = ["@unique"]

[model.User.rollNumber]
type = "String"
attributes = ["@unique"]

[model.User.department]
type = "enum.Department"

[model.User.role]
type = "enum.UserRole"
default = "COORDINATOR"

[model.User.password]
type = "String"

[model.User.salt]
type = "String"

[model.User.profilePic]
type = "String?"

[model.User.coverPic]
type = "String?"

[model.User.mobile]
type = "String"

[model.User.upi]
type = "String?"

[model.User.enabled]
type = "Boolean"
default = false

[model.User.verified]
type = "Boolean"
default = false